language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t neethumohan1212/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true neethumohan1212/react-docker npm run test